x-app: &app_image
  build:
    context: .
    dockerfile: Dockerfile
  image: parcels-backend:1

services:
  db:
    image: postgres:18-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:8.8.2-alpine
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5

  api:
    <<: *app_image
    restart: always
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

  migrate:
    <<: *app_image
    command: [ "alembic", "upgrade", "head" ]
    env_file:
      - .env
    environment:
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy

  worker:
    <<: *app_image
    restart: always
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
    command: ["celery", "-A", "app.core.celery:celery_app", "worker", "--loglevel=info"]
    depends_on:
      redis:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

  beat:
    <<: *app_image
    restart: always
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
    command: ["celery", "-A", "app.core.celery:celery_app", "beat", "--loglevel=info"]
    depends_on:
      redis:
        condition: service_healthy

volumes:
  postgres_data: