"""Создание таблиц посылок

Revision ID: 0aec2c4ca7c6
Revises: 
Create Date: 2026-08-15 18:45:24.474701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aec2c4ca7c6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parcel_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('parcels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('weight', sa.DECIMAL(precision=6, scale=2), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('dollar_price', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('delivery_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('user_session', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['parcel_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_type', 'parcels', ['user_session', 'type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_session_type', table_name='parcels')
    op.drop_table('parcels')
    op.drop_table('parcel_types')
    # ### end Alembic commands ###
